/**
 * Apaleo Finance API
 * Everything around the Folio, Invoices and Accounting.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

import { FormBuilder, FormGroup }                                               from '@angular/forms';
import { ResponseModel }                                                        from '../../models';
import { getControl, adjustDefaultControls, prepareFormGroup }                  from '../../functions.model';
import { BuildFormOptions, ApaleoPropertyMetaData, ApaleoEnumPropertyMetaData } from '../../types';

export interface MoveLineItemModel {
    /**
     * Id of the source folio
     */
    sourceFolioId: string;

    /**
     * Id of the target folio
     */
    targetFolioId: string;

}

export type MoveLineItemModelWithRawHttp = MoveLineItemModel & ResponseModel<MoveLineItemModel>;

export namespace MoveLineItemModel {
    export const $metaData = { 
        sourceFolioId: Object.freeze({ 
            isRequired: true,
            type: 'string',
            isPrimitiveType: true,
        } as ApaleoPropertyMetaData),
        targetFolioId: Object.freeze({ 
            isRequired: true,
            type: 'string',
            isPrimitiveType: true,
        } as ApaleoPropertyMetaData),
    };

    export function $buildForm(fb: FormBuilder, options?: BuildFormOptions<MoveLineItemModel>): FormGroup {
        const defaultControls = { 
            sourceFolioId: getControl($metaData.sourceFolioId, options, 'sourceFolioId'),
            targetFolioId: getControl($metaData.targetFolioId, options, 'targetFolioId'),
        };
        const group = fb.group(adjustDefaultControls(defaultControls, options));
        prepareFormGroup(group, $metaData, options);

        return group;
    }
}

