/**
 * Apaleo Rates API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

import { FormBuilder, FormGroup }                              from '@angular/forms';
import { IBuildFormOptions, IApaleoPropertyMetaData }          from '../../types';
import { ResponseModel }                                       from '../../models';
import { getControl, adjustDefaultControls, prepareFormGroup } from '../../functions.model';

export interface OfferModel {
    /**
     * The earliest arrival date and time for this offer
     */
    arrival: Date;

    /**
     * The latest departure date and time for this offer
     */
    departure: Date;

    /**
     * The unit type for which the following offers apply
     */
    unitType: models.EmbeddedUnitTypeModel;

    /**
     * The number of available units for that offer
     */
    availableUnits: number;

    /**
     * The rate plan for this offer
     */
    ratePlan: models.EmbeddedRatePlanModel;

    /**
     * The price for the whole stay
     */
    totalAmount: number;

    /**
     * The breakdown for each time slice for this offer
     */
    timeSlices: Array<models.OfferTimeSliceModel>;

}

export type OfferModelWithRawHttp = OfferModel & ResponseModel<OfferModel>;

export namespace OfferModel {
    export const $metaData = { 
        arrival: Object.freeze({ 
            isRequired: true,
            type: 'Date',
            isPrimitiveType: true,
        } as IApaleoPropertyMetaData),
        departure: Object.freeze({ 
            isRequired: true,
            type: 'Date',
            isPrimitiveType: true,
        } as IApaleoPropertyMetaData),
        unitType: Object.freeze({ 
            isRequired: true,
            type: 'models.EmbeddedUnitTypeModel',
        } as IApaleoPropertyMetaData),
        availableUnits: Object.freeze({ 
            isRequired: true,
            type: 'number',
            isPrimitiveType: true,
        } as IApaleoPropertyMetaData),
        ratePlan: Object.freeze({ 
            isRequired: true,
            type: 'models.EmbeddedRatePlanModel',
        } as IApaleoPropertyMetaData),
        totalAmount: Object.freeze({ 
            isRequired: true,
            type: 'number',
            isPrimitiveType: true,
        } as IApaleoPropertyMetaData),
        timeSlices: Object.freeze({ 
            isRequired: true,
            type: 'Array<models.OfferTimeSliceModel>',
            isListContainer: true,
        } as IApaleoPropertyMetaData),
    };

    export function $buildForm(fb: FormBuilder, options?: IBuildFormOptions<OfferModel>): FormGroup {
        const defaultControls = { 
            arrival: getControl($metaData.arrival, options, 'arrival'),
            departure: getControl($metaData.departure, options, 'departure'),
            unitType: models.EmbeddedUnitTypeModel.$buildForm(fb),
            availableUnits: getControl($metaData.availableUnits, options, 'availableUnits'),
            ratePlan: models.EmbeddedRatePlanModel.$buildForm(fb),
            totalAmount: getControl($metaData.totalAmount, options, 'totalAmount'),
        };
        const group = fb.group(adjustDefaultControls(defaultControls, options));
        prepareFormGroup(group, $metaData, options);

        return group;
    }
}

