/**
 * Apaleo Rates API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

import { FormBuilder, FormGroup }                         from '@angular/forms';
import { IBuildFormOptions, IApaleoPropertyMetaData }     from '../../types';
import { ResponseModel }                                  from '../../models';
import { getControl, adjustDefaultControls, setMetaData } from '../../functions.model';

export interface RatePlanModel {
    /**
     * The rateplan id
     */
    id?: string;

    /**
     * The code for the rateplan that can be shown in reports and table views
     */
    code?: string;

    /**
     * The name for the rateplan
     */
    name?: { [key: string]: string; };

    /**
     * The description for the rateplan
     */
    description?: { [key: string]: string; };

    /**
     * The default price for the rateplan
     */
    defaultPrice?: number;

    /**
     * The property to which the rateplan belongs to
     */
    property?: models.EmbeddedPropertyModel;

    /**
     * Unit types linked to the rateplan
     */
    unitTypes?: Array<models.EmbeddedUnitTypeModel>;

}

export type RatePlanModelWithRawHttp = RatePlanModel & ResponseModel<RatePlanModel>;

export namespace RatePlanModel {
    export const $metaData = { 
        id: Object.freeze({ 
            type: 'string',
            isPrimitiveType: true,
        } as IApaleoPropertyMetaData),
        code: Object.freeze({ 
            type: 'string',
            isPrimitiveType: true,
        } as IApaleoPropertyMetaData),
        name: Object.freeze({ 
            type: '{ [key: string]: string; }',
            isPrimitiveType: true,
            isMapContainer: true,
        } as IApaleoPropertyMetaData),
        description: Object.freeze({ 
            type: '{ [key: string]: string; }',
            isPrimitiveType: true,
            isMapContainer: true,
        } as IApaleoPropertyMetaData),
        defaultPrice: Object.freeze({ 
            type: 'number',
            isPrimitiveType: true,
        } as IApaleoPropertyMetaData),
        property: Object.freeze({ 
            type: 'models.EmbeddedPropertyModel',
        } as IApaleoPropertyMetaData),
        unitTypes: Object.freeze({ 
            type: 'Array<models.EmbeddedUnitTypeModel>',
            isListContainer: true,
        } as IApaleoPropertyMetaData),
    };

    export function $buildForm(fb: FormBuilder, options?: IBuildFormOptions<RatePlanModel>): FormGroup {
        const defaultControls = { 
            id: getControl($metaData.id, options, 'id'),
            code: getControl($metaData.code, options, 'code'),
            defaultPrice: getControl($metaData.defaultPrice, options, 'defaultPrice'),
            property: models.EmbeddedPropertyModel.$buildForm(fb),
        };
        const group = fb.group(adjustDefaultControls(defaultControls, options));
        setMetaData(group, $metaData);

        return group;
    }
}

