/**
 * Rates Management
 * Manage the rate plans and rates to rent out your inventory at the best price.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

import { FormBuilder, FormGroup }                                               from '@angular/forms';
import { ResponseModel }                                                        from '../../models';
import { getControl, adjustDefaultControls, prepareFormGroup }                  from '../../functions.model';
import { BuildFormOptions, ApaleoPropertyMetaData, ApaleoEnumPropertyMetaData } from '../../types';

export interface ReplaceRateModel {
    /**
     * Date and time the rate begins
     */
    from: Date;

    /**
     * Date and time the rate ends
     */
    to: Date;

    /**
     * The rate amount
     */
    amount: number;

}

export type ReplaceRateModelWithRawHttp = ReplaceRateModel & ResponseModel<ReplaceRateModel>;

export namespace ReplaceRateModel {
    export const $metaData = { 
        from: Object.freeze({ 
            isRequired: true,
            type: 'Date',
            isPrimitiveType: true,
        } as ApaleoPropertyMetaData),
        to: Object.freeze({ 
            isRequired: true,
            type: 'Date',
            isPrimitiveType: true,
        } as ApaleoPropertyMetaData),
        amount: Object.freeze({ 
            isRequired: true,
            type: 'number',
            isPrimitiveType: true,
        } as ApaleoPropertyMetaData),
    };

    export function $buildForm(fb: FormBuilder, options?: BuildFormOptions<ReplaceRateModel>): FormGroup {
        const defaultControls = { 
            from: getControl($metaData.from, options, 'from'),
            to: getControl($metaData.to, options, 'to'),
            amount: getControl($metaData.amount, options, 'amount'),
        };
        const group = fb.group(adjustDefaultControls(defaultControls, options));
        prepareFormGroup(group, $metaData, options);

        return group;
    }
}

