/**
 * Apaleo UI API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * With this request you can setup a new account with an admin user
 */
export interface PostAccountRequest {
    /**
     * The code for the account that can be shown in reports and table views
     */
    code: string;

    /**
     * The name for the account, which usually should be the company name
     */
    name: string;

    /**
     * The street of the address for the account
     */
    street: string;

    /**
     * The postal code of the address for the account
     */
    postalCode: string;

    /**
     * The city of the address for the account
     */
    city: string;

    /**
     * The country of the address for the account
     */
    country: string;

    /**
     * The admin user for this account
     */
    adminUser: models.User;

}
