/**
 * Account
 * Manage accounts, subscriptions and more.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-variable member-ordering */

import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/map';

import { Inject, Injectable, LOCALE_ID }                           from '@angular/core';
import { Http, Headers, URLSearchParams, Response, RequestMethod } from '@angular/http';

import * as models                                                 from '../model/models';
import { BASE_PATH, COLLECTION_FORMATS }                           from '../../variables';
import { ApaleoRequestOptions, ResponseModel }                     from '../../models';
import { Configuration }                                           from '../../configuration';
import { callApiEndpoint }                                         from '../../functions.api';



export namespace accountAccountsByCodeGet {
    export interface Params {
        /**
        * The code of the account.
        */
        code: string;
    }
    
}
export namespace accountAccountsByCodeHead {
    export interface Params {
        /**
        * The code of the account.
        */
        code: string;
    }
    
}
export namespace accountAccountsByCodePut {
    export interface Params {
        /**
        * The code of the account.
        */
        code: string;
        /**
        * The definition of the account.
        */
        requestBody: models.ReplaceAccountModel;
    }
    
}
export namespace accountAccountsPost {
    export interface Params {
        /**
        * The definition of the account.
        */
        requestBody: models.CreateAccountModel;
    }
    
}

@Injectable()
export class AccountApi {
    public readonly defaultHeaders: Headers = new Headers();

    constructor(
        protected readonly http: Http, 
        protected readonly configuration: Configuration,
        @Inject(LOCALE_ID) protected readonly locale: string, 
        @Inject(BASE_PATH) protected readonly basePath: string) {

        this.defaultHeaders.append('Accept-Language', locale);
    }

    /**
     * Returns a specific account.
     * Retrieves an account, specified by its code.
     * @param code The code of the account.
     */
    public accountAccountsByCodeGet(params: accountAccountsByCodeGet.Params, $options?: ApaleoRequestOptions)
        : Observable<models.AccountModel | undefined> {
        return this.accountAccountsByCodeGetWithRawHttp(params, $options)
            .map(response => response.$hasValue(response) ? response : undefined);
    }

    /**
     * Checks if an account exists.
     * Check if an account exists by code.
     * @param code The code of the account.
     */
    public accountAccountsByCodeHead(params: accountAccountsByCodeHead.Params, $options?: ApaleoRequestOptions)
        : Observable<void> {
        return this.accountAccountsByCodeHeadWithRawHttp(params, $options)
            .map(response => response.$hasValue(response) ? response : undefined);
    }

    /**
     * Replaces an existing account.
     * Completely replaces an account with the new definition passed in. The old data will be lost.
     * @param code The code of the account.
     * @param requestBody The definition of the account.
     */
    public accountAccountsByCodePut(params: accountAccountsByCodePut.Params, $options?: ApaleoRequestOptions)
        : Observable<void> {
        return this.accountAccountsByCodePutWithRawHttp(params, $options)
            .map(response => response.$hasValue(response) ? response : undefined);
    }

    /**
     * Creates an account with an admin user.
     * Use this call to create a new account.
     * @param requestBody The definition of the account.
     */
    public accountAccountsPost(params: accountAccountsPost.Params, $options?: ApaleoRequestOptions)
        : Observable<void> {
        return this.accountAccountsPostWithRawHttp(params, $options)
            .map(response => response.$hasValue(response) ? response : undefined);
    }


    /**
     * Returns a specific account.
     * Retrieves an account, specified by its code.
     * @param code The code of the account.
     */
    public accountAccountsByCodeGetWithRawHttp(params: accountAccountsByCodeGet.Params, $options?: ApaleoRequestOptions)
        : Observable<ResponseModel<models.AccountModel>> {
        return this.accountAccountsByCodeGetWithHttpInfo(params, $options)
            .map((response: Response) => new ResponseModel(response));
    }

    /**
     * Checks if an account exists.
     * Check if an account exists by code.
     * @param code The code of the account.
     */
    public accountAccountsByCodeHeadWithRawHttp(params: accountAccountsByCodeHead.Params, $options?: ApaleoRequestOptions)
        : Observable<ResponseModel<void>> {
        return this.accountAccountsByCodeHeadWithHttpInfo(params, $options)
            .map((response: Response) => new ResponseModel(response));
    }

    /**
     * Replaces an existing account.
     * Completely replaces an account with the new definition passed in. The old data will be lost.
     * @param code The code of the account.
     * @param requestBody The definition of the account.
     */
    public accountAccountsByCodePutWithRawHttp(params: accountAccountsByCodePut.Params, $options?: ApaleoRequestOptions)
        : Observable<ResponseModel<void>> {
        return this.accountAccountsByCodePutWithHttpInfo(params, $options)
            .map((response: Response) => new ResponseModel(response));
    }

    /**
     * Creates an account with an admin user.
     * Use this call to create a new account.
     * @param requestBody The definition of the account.
     */
    public accountAccountsPostWithRawHttp(params: accountAccountsPost.Params, $options?: ApaleoRequestOptions)
        : Observable<ResponseModel<void>> {
        return this.accountAccountsPostWithHttpInfo(params, $options)
            .map((response: Response) => new ResponseModel(response));
    }


    /**
     * Returns a specific account.
     * Retrieves an account, specified by its code.
     * @param code The code of the account.
     */
    private accountAccountsByCodeGetWithHttpInfo(params: accountAccountsByCodeGet.Params, $options?: ApaleoRequestOptions): Observable<Response> {
        params = params || {};
        const path = this.basePath + '/account/accounts/${code}'
                    .replace('${' + 'code' + '}', String(params.code));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'code' is not null or undefined
        if (params.code === null || params.code === undefined) {
            throw new Error('Required parameter code was null or undefined when calling accountAccountsByCodeGet.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];

        // authentication (oauth2) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        return callApiEndpoint(
            this.http, 
            path,
            headers,
            {
                method: RequestMethod.Get,
                headers: headers,
                search: queryParameters,
                withCredentials: this.configuration.withCredentials
            },
            Object.assign({}, this.configuration, $options),
            retryTimesToGo => {
                $options = $options || {};
                $options.retryTimes = retryTimesToGo;

                return this.accountAccountsByCodeGetWithHttpInfo(params, $options);
            }
        )
    }

    /**
     * Checks if an account exists.
     * Check if an account exists by code.
     * @param code The code of the account.
     */
    private accountAccountsByCodeHeadWithHttpInfo(params: accountAccountsByCodeHead.Params, $options?: ApaleoRequestOptions): Observable<Response> {
        params = params || {};
        const path = this.basePath + '/account/accounts/${code}'
                    .replace('${' + 'code' + '}', String(params.code));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'code' is not null or undefined
        if (params.code === null || params.code === undefined) {
            throw new Error('Required parameter code was null or undefined when calling accountAccountsByCodeHead.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
        ];

        // authentication (oauth2) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        return callApiEndpoint(
            this.http, 
            path,
            headers,
            {
                method: RequestMethod.Head,
                headers: headers,
                search: queryParameters,
                withCredentials: this.configuration.withCredentials
            },
            Object.assign({}, this.configuration, $options),
            retryTimesToGo => {
                $options = $options || {};
                $options.retryTimes = retryTimesToGo;

                return this.accountAccountsByCodeHeadWithHttpInfo(params, $options);
            }
        )
    }

    /**
     * Replaces an existing account.
     * Completely replaces an account with the new definition passed in. The old data will be lost.
     * @param code The code of the account.
     * @param requestBody The definition of the account.
     */
    private accountAccountsByCodePutWithHttpInfo(params: accountAccountsByCodePut.Params, $options?: ApaleoRequestOptions): Observable<Response> {
        params = params || {};
        const path = this.basePath + '/account/accounts/${code}'
                    .replace('${' + 'code' + '}', String(params.code));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'code' is not null or undefined
        if (params.code === null || params.code === undefined) {
            throw new Error('Required parameter code was null or undefined when calling accountAccountsByCodePut.');
        }
        // verify required parameter 'requestBody' is not null or undefined
        if (params.requestBody === null || params.requestBody === undefined) {
            throw new Error('Required parameter requestBody was null or undefined when calling accountAccountsByCodePut.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/json-patch+json'
        ];

        // to determine the Accept header
        let produces: string[] = [
        ];

        // authentication (oauth2) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        headers.set('Content-Type', 'application/json');

        return callApiEndpoint(
            this.http, 
            path,
            headers,
            {
                method: RequestMethod.Put,
                headers: headers,
                body: params.requestBody == null ? '' : params.requestBody, // https://github.com/angular/angular/issues/10612
                search: queryParameters,
                withCredentials: this.configuration.withCredentials
            },
            Object.assign({}, this.configuration, $options),
            retryTimesToGo => {
                $options = $options || {};
                $options.retryTimes = retryTimesToGo;

                return this.accountAccountsByCodePutWithHttpInfo(params, $options);
            }
        )
    }

    /**
     * Creates an account with an admin user.
     * Use this call to create a new account.
     * @param requestBody The definition of the account.
     */
    private accountAccountsPostWithHttpInfo(params: accountAccountsPost.Params, $options?: ApaleoRequestOptions): Observable<Response> {
        params = params || {};
        const path = this.basePath + '/account/accounts';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'requestBody' is not null or undefined
        if (params.requestBody === null || params.requestBody === undefined) {
            throw new Error('Required parameter requestBody was null or undefined when calling accountAccountsPost.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/json-patch+json'
        ];

        // to determine the Accept header
        let produces: string[] = [
        ];

        // authentication (oauth2) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        headers.set('Content-Type', 'application/json');

        return callApiEndpoint(
            this.http, 
            path,
            headers,
            {
                method: RequestMethod.Post,
                headers: headers,
                body: params.requestBody == null ? '' : params.requestBody, // https://github.com/angular/angular/issues/10612
                search: queryParameters,
                withCredentials: this.configuration.withCredentials
            },
            Object.assign({}, this.configuration, $options),
            retryTimesToGo => {
                $options = $options || {};
                $options.retryTimes = retryTimesToGo;

                return this.accountAccountsPostWithHttpInfo(params, $options);
            }
        )
    }

}
