export * from './PropertyApi';
import { PropertyApi } from './PropertyApi';
export * from './PropertySettingsApi';
import { PropertySettingsApi } from './PropertySettingsApi';
export * from './UnitApi';
import { UnitApi } from './UnitApi';
export * from './UnitAvailabilityApi';
import { UnitAvailabilityApi } from './UnitAvailabilityApi';
export * from './UnitTypeApi';
import { UnitTypeApi } from './UnitTypeApi';
export const APIS = [PropertyApi, PropertySettingsApi, UnitApi, UnitAvailabilityApi, UnitTypeApi];
