/**
 * Apaleo Inventory API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Inject, Injectable, LOCALE_ID }                           from '@angular/core';
import { Http, Headers, URLSearchParams, Response, RequestMethod } from '@angular/http';

import { Observable }                                              from 'rxjs/Rx';
import 'rxjs/add/operator/map';

import * as models                                                 from '../model/models';
import { BASE_PATH, COLLECTION_FORMATS }                           from '../../variables';
import { IRequestOptions, ResponseModel }                          from '../../models';
import { Configuration }                                           from '../../configuration';
import { callApiEndpoint }                                         from '../../functions.api';

/* tslint:disable:no-unused-variable member-ordering */


export interface inventoryV1PropertiesByIdSettingsGetParams {
    /**
     * The id of the property.
     */
    id: string;
}
export interface inventoryV1PropertiesByIdSettingsPutParams {
    /**
     * The id of the property.
     */
    id: string;
    /**
     * The definition of the property settings.
     */
    requestBody: models.ReplacePropertySettingsModel;
}

@Injectable()
export class PropertySettingsApi {
    public defaultHeaders: Headers = new Headers();

    constructor(
        protected readonly http: Http, 
        protected readonly configuration: Configuration,
        @Inject(LOCALE_ID) protected readonly locale: string, 
        @Inject(BASE_PATH) protected readonly basePath: string) {

        this.defaultHeaders.append('Accept-Language', locale);
    }

    /**
     * Get property settings
     * Get base settings for a property
     * @param id The id of the property.
     */
    public inventoryV1PropertiesByIdSettingsGet(params: inventoryV1PropertiesByIdSettingsGetParams, $options?: IRequestOptions)
        : Observable<models.PropertySettingsModel | undefined> {
        return this.inventoryV1PropertiesByIdSettingsGetWithRawHttp(params, $options)
            .map(response => response.$hasValue(response) ? response : undefined);
    }

    /**
     * Replaces base settings for the property
     * Use this call to modify the base settings of the property.
     * @param id The id of the property.
     * @param requestBody The definition of the property settings.
     */
    public inventoryV1PropertiesByIdSettingsPut(params: inventoryV1PropertiesByIdSettingsPutParams, $options?: IRequestOptions)
        : Observable<void> {
        return this.inventoryV1PropertiesByIdSettingsPutWithRawHttp(params, $options)
            .map(response => response.$hasValue(response) ? response : undefined);
    }


    /**
     * Get property settings
     * Get base settings for a property
     * @param id The id of the property.
     */
    public inventoryV1PropertiesByIdSettingsGetWithRawHttp(params: inventoryV1PropertiesByIdSettingsGetParams, $options?: IRequestOptions)
        : Observable<ResponseModel<models.PropertySettingsModel>> {
        return this.inventoryV1PropertiesByIdSettingsGetWithHttpInfo(params, $options)
            .map((response: Response) => new ResponseModel(response));
    }

    /**
     * Replaces base settings for the property
     * Use this call to modify the base settings of the property.
     * @param id The id of the property.
     * @param requestBody The definition of the property settings.
     */
    public inventoryV1PropertiesByIdSettingsPutWithRawHttp(params: inventoryV1PropertiesByIdSettingsPutParams, $options?: IRequestOptions)
        : Observable<ResponseModel<void>> {
        return this.inventoryV1PropertiesByIdSettingsPutWithHttpInfo(params, $options)
            .map((response: Response) => new ResponseModel(response));
    }


    /**
     * Get property settings
     * Get base settings for a property
     * @param id The id of the property.
     */
    private inventoryV1PropertiesByIdSettingsGetWithHttpInfo(params: inventoryV1PropertiesByIdSettingsGetParams, $options?: IRequestOptions): Observable<Response> {
        params = params || {};
        const path = this.basePath + '/inventory/v1/properties/${id}/settings'
                    .replace('${' + 'id' + '}', String(params.id));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'id' is not null or undefined
        if (params.id === null || params.id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling inventoryV1PropertiesByIdSettingsGet.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'text/plain', 
            'application/json', 
            'text/json'
        ];

        // authentication (oauth2) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        return callApiEndpoint(
            this.http, 
            path,
            headers,
            {
                method: RequestMethod.Get,
                headers: headers,
                search: queryParameters,
                withCredentials: this.configuration.withCredentials
            },
            Object.assign({}, this.configuration, $options),
            retryTimesToGo => {
                $options = $options || {};
                $options.retryTimes = retryTimesToGo;

                return this.inventoryV1PropertiesByIdSettingsGetWithHttpInfo(params, $options);
            }
        )
    }

    /**
     * Replaces base settings for the property
     * Use this call to modify the base settings of the property.
     * @param id The id of the property.
     * @param requestBody The definition of the property settings.
     */
    private inventoryV1PropertiesByIdSettingsPutWithHttpInfo(params: inventoryV1PropertiesByIdSettingsPutParams, $options?: IRequestOptions): Observable<Response> {
        params = params || {};
        const path = this.basePath + '/inventory/v1/properties/${id}/settings'
                    .replace('${' + 'id' + '}', String(params.id));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'id' is not null or undefined
        if (params.id === null || params.id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling inventoryV1PropertiesByIdSettingsPut.');
        }
        // verify required parameter 'requestBody' is not null or undefined
        if (params.requestBody === null || params.requestBody === undefined) {
            throw new Error('Required parameter requestBody was null or undefined when calling inventoryV1PropertiesByIdSettingsPut.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json', 
            'text/json', 
            'application/json-patch+json'
        ];

        // to determine the Accept header
        let produces: string[] = [
        ];

        // authentication (oauth2) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        headers.set('Content-Type', 'application/json');

        return callApiEndpoint(
            this.http, 
            path,
            headers,
            {
                method: RequestMethod.Put,
                headers: headers,
                body: params.requestBody == null ? '' : JSON.stringify(params.requestBody), // https://github.com/angular/angular/issues/10612
                search: queryParameters,
                withCredentials: this.configuration.withCredentials
            },
            Object.assign({}, this.configuration, $options),
            retryTimesToGo => {
                $options = $options || {};
                $options.retryTimes = retryTimesToGo;

                return this.inventoryV1PropertiesByIdSettingsPutWithHttpInfo(params, $options);
            }
        )
    }

}
