/**
 * Apaleo Inventory API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Inject, Injectable, LOCALE_ID }                           from '@angular/core';
import { Http, Headers, URLSearchParams, Response, RequestMethod } from '@angular/http';

import { Observable }                                              from 'rxjs/Rx';
import 'rxjs/add/operator/map';

import * as models                                                 from '../model/models';
import { BASE_PATH, COLLECTION_FORMATS }                           from '../../variables';
import { IRequestOptions, ResponseModel }                          from '../../models';
import { Configuration }                                           from '../../configuration';
import { callApiEndpoint }                                         from '../../functions.api';

/* tslint:disable:no-unused-variable member-ordering */


@Injectable()
export class UnitTypeApi {
    public defaultHeaders: Headers = new Headers();

    constructor(
        protected readonly http: Http, 
        protected readonly configuration: Configuration,
        @Inject(LOCALE_ID) protected readonly locale: string, 
        @Inject(BASE_PATH) protected readonly basePath: string) {

        this.defaultHeaders.append('Accept-Language', locale);
    }

    /**
     * Delete a unit type
     * Use this call to delete a unit type.
     * @param id The id of the unit type.
     */
    public inventoryV1UnitTypesByIdDelete(id: string, $options?: IRequestOptions)
        : Observable<void> {
        return this.inventoryV1UnitTypesByIdDeleteWithRawHttp(id, $options)
            .map(response => response.$hasValue(response) ? response : undefined);
    }

    /**
     * Get a unit type
     * Get a unit type by id.
     * @param id The id of the unit type.
     * @param languages &#39;all&#39; or comma separated list of language codes
     */
    public inventoryV1UnitTypesByIdGet(id: string, languages?: Array<string>, $options?: IRequestOptions)
        : Observable<models.UnitTypeModel | undefined> {
        return this.inventoryV1UnitTypesByIdGetWithRawHttp(id, languages, $options)
            .map(response => response.$hasValue(response) ? response : undefined);
    }

    /**
     * Check if a unit type exists
     * Check if a unit type exists by id.
     * @param id The id of the unit type.
     */
    public inventoryV1UnitTypesByIdHead(id: string, $options?: IRequestOptions)
        : Observable<void> {
        return this.inventoryV1UnitTypesByIdHeadWithRawHttp(id, $options)
            .map(response => response.$hasValue(response) ? response : undefined);
    }

    /**
     * Replace a unit type
     * Use this call to modify a unit type.
     * @param id The id of the unit type.
     * @param requestBody The definition of the unit type.
     */
    public inventoryV1UnitTypesByIdPut(id: string, requestBody: models.ReplaceUnitTypeModel, $options?: IRequestOptions)
        : Observable<void> {
        return this.inventoryV1UnitTypesByIdPutWithRawHttp(id, requestBody, $options)
            .map(response => response.$hasValue(response) ? response : undefined);
    }

    /**
     * Get all unit types, or all unit types for a property
     * Get the list of unit types.
     * @param propertyId Return unit types for specific property
     * @param pageNumber Page number, starting from 1. Results in 204 if there are no items on that page. If the value is lower than 1, will be set to 1
     * @param pageSize Page size
     */
    public inventoryV1UnitTypesGet(propertyId?: string, pageNumber?: number, pageSize?: number, $options?: IRequestOptions)
        : Observable<models.UnitTypeListModel | undefined> {
        return this.inventoryV1UnitTypesGetWithRawHttp(propertyId, pageNumber, pageSize, $options)
            .map(response => response.$hasValue(response) ? response : undefined);
    }

    /**
     * Create a unit type
     * Use this call to create a new unit type.
     * @param requestBody The definition of the unit type.
     */
    public inventoryV1UnitTypesPost(requestBody: models.CreateUnitTypeModel, $options?: IRequestOptions)
        : Observable<models.UnitTypeCreatedModel | undefined> {
        return this.inventoryV1UnitTypesPostWithRawHttp(requestBody, $options)
            .map(response => response.$hasValue(response) ? response : undefined);
    }

    /**
     * Return total count of unit types
     * Return total count of unit types
     */
    public inventoryV1UnitTypescountGet($options?: IRequestOptions)
        : Observable<number | undefined> {
        return this.inventoryV1UnitTypescountGetWithRawHttp($options)
            .map(response => response.$hasValue(response) ? response : undefined);
    }


    /**
     * Delete a unit type
     * Use this call to delete a unit type.
     * @param id The id of the unit type.
     */
    public inventoryV1UnitTypesByIdDeleteWithRawHttp(id: string, $options?: IRequestOptions)
        : Observable<ResponseModel<void>> {
        return this.inventoryV1UnitTypesByIdDeleteWithHttpInfo(id, $options)
            .map((response: Response) => new ResponseModel(response));
    }

    /**
     * Get a unit type
     * Get a unit type by id.
     * @param id The id of the unit type.
     * @param languages &#39;all&#39; or comma separated list of language codes
     */
    public inventoryV1UnitTypesByIdGetWithRawHttp(id: string, languages?: Array<string>, $options?: IRequestOptions)
        : Observable<ResponseModel<models.UnitTypeModel>> {
        return this.inventoryV1UnitTypesByIdGetWithHttpInfo(id, languages, $options)
            .map((response: Response) => new ResponseModel(response));
    }

    /**
     * Check if a unit type exists
     * Check if a unit type exists by id.
     * @param id The id of the unit type.
     */
    public inventoryV1UnitTypesByIdHeadWithRawHttp(id: string, $options?: IRequestOptions)
        : Observable<ResponseModel<void>> {
        return this.inventoryV1UnitTypesByIdHeadWithHttpInfo(id, $options)
            .map((response: Response) => new ResponseModel(response));
    }

    /**
     * Replace a unit type
     * Use this call to modify a unit type.
     * @param id The id of the unit type.
     * @param requestBody The definition of the unit type.
     */
    public inventoryV1UnitTypesByIdPutWithRawHttp(id: string, requestBody: models.ReplaceUnitTypeModel, $options?: IRequestOptions)
        : Observable<ResponseModel<void>> {
        return this.inventoryV1UnitTypesByIdPutWithHttpInfo(id, requestBody, $options)
            .map((response: Response) => new ResponseModel(response));
    }

    /**
     * Get all unit types, or all unit types for a property
     * Get the list of unit types.
     * @param propertyId Return unit types for specific property
     * @param pageNumber Page number, starting from 1. Results in 204 if there are no items on that page. If the value is lower than 1, will be set to 1
     * @param pageSize Page size
     */
    public inventoryV1UnitTypesGetWithRawHttp(propertyId?: string, pageNumber?: number, pageSize?: number, $options?: IRequestOptions)
        : Observable<ResponseModel<models.UnitTypeListModel>> {
        return this.inventoryV1UnitTypesGetWithHttpInfo(propertyId, pageNumber, pageSize, $options)
            .map((response: Response) => new ResponseModel(response));
    }

    /**
     * Create a unit type
     * Use this call to create a new unit type.
     * @param requestBody The definition of the unit type.
     */
    public inventoryV1UnitTypesPostWithRawHttp(requestBody: models.CreateUnitTypeModel, $options?: IRequestOptions)
        : Observable<ResponseModel<models.UnitTypeCreatedModel>> {
        return this.inventoryV1UnitTypesPostWithHttpInfo(requestBody, $options)
            .map((response: Response) => new ResponseModel(response));
    }

    /**
     * Return total count of unit types
     * Return total count of unit types
     */
    public inventoryV1UnitTypescountGetWithRawHttp($options?: IRequestOptions)
        : Observable<ResponseModel<number>> {
        return this.inventoryV1UnitTypescountGetWithHttpInfo($options)
            .map((response: Response) => new ResponseModel(response));
    }


    /**
     * Delete a unit type
     * Use this call to delete a unit type.
     * @param id The id of the unit type.
     */
    private inventoryV1UnitTypesByIdDeleteWithHttpInfo(id: string, $options?: IRequestOptions): Observable<Response> {
        const path = this.basePath + '/inventory/v1/unit-types/${id}'
                    .replace('${' + 'id' + '}', String(id));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling inventoryV1UnitTypesByIdDelete.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
        ];

        // authentication (oauth2) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        return callApiEndpoint(
            this.http, 
            path,
            headers,
            {
                method: RequestMethod.Delete,
                headers: headers,
                search: queryParameters,
                withCredentials: this.configuration.withCredentials
            },
            Object.assign({}, this.configuration, $options),
            retryTimesToGo => {
                $options = $options || {};
                $options.retryTimes = retryTimesToGo;

                return this.inventoryV1UnitTypesByIdDeleteWithHttpInfo(id, $options);
            }
        )
    }

    /**
     * Get a unit type
     * Get a unit type by id.
     * @param id The id of the unit type.
     * @param languages &#39;all&#39; or comma separated list of language codes
     */
    private inventoryV1UnitTypesByIdGetWithHttpInfo(id: string, languages?: Array<string>, $options?: IRequestOptions): Observable<Response> {
        const path = this.basePath + '/inventory/v1/unit-types/${id}'
                    .replace('${' + 'id' + '}', String(id));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling inventoryV1UnitTypesByIdGet.');
        }
        if (languages) {
            queryParameters.set('languages', languages.join(COLLECTION_FORMATS['csv']));
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'text/plain', 
            'application/json', 
            'text/json'
        ];

        // authentication (oauth2) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        return callApiEndpoint(
            this.http, 
            path,
            headers,
            {
                method: RequestMethod.Get,
                headers: headers,
                search: queryParameters,
                withCredentials: this.configuration.withCredentials
            },
            Object.assign({}, this.configuration, $options),
            retryTimesToGo => {
                $options = $options || {};
                $options.retryTimes = retryTimesToGo;

                return this.inventoryV1UnitTypesByIdGetWithHttpInfo(id, languages, $options);
            }
        )
    }

    /**
     * Check if a unit type exists
     * Check if a unit type exists by id.
     * @param id The id of the unit type.
     */
    private inventoryV1UnitTypesByIdHeadWithHttpInfo(id: string, $options?: IRequestOptions): Observable<Response> {
        const path = this.basePath + '/inventory/v1/unit-types/${id}'
                    .replace('${' + 'id' + '}', String(id));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling inventoryV1UnitTypesByIdHead.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
        ];

        // authentication (oauth2) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        return callApiEndpoint(
            this.http, 
            path,
            headers,
            {
                method: RequestMethod.Head,
                headers: headers,
                search: queryParameters,
                withCredentials: this.configuration.withCredentials
            },
            Object.assign({}, this.configuration, $options),
            retryTimesToGo => {
                $options = $options || {};
                $options.retryTimes = retryTimesToGo;

                return this.inventoryV1UnitTypesByIdHeadWithHttpInfo(id, $options);
            }
        )
    }

    /**
     * Replace a unit type
     * Use this call to modify a unit type.
     * @param id The id of the unit type.
     * @param requestBody The definition of the unit type.
     */
    private inventoryV1UnitTypesByIdPutWithHttpInfo(id: string, requestBody: models.ReplaceUnitTypeModel, $options?: IRequestOptions): Observable<Response> {
        const path = this.basePath + '/inventory/v1/unit-types/${id}'
                    .replace('${' + 'id' + '}', String(id));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling inventoryV1UnitTypesByIdPut.');
        }
        // verify required parameter 'requestBody' is not null or undefined
        if (requestBody === null || requestBody === undefined) {
            throw new Error('Required parameter requestBody was null or undefined when calling inventoryV1UnitTypesByIdPut.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json', 
            'text/json', 
            'application/json-patch+json'
        ];

        // to determine the Accept header
        let produces: string[] = [
        ];

        // authentication (oauth2) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        headers.set('Content-Type', 'application/json');

        return callApiEndpoint(
            this.http, 
            path,
            headers,
            {
                method: RequestMethod.Put,
                headers: headers,
                body: requestBody == null ? '' : JSON.stringify(requestBody), // https://github.com/angular/angular/issues/10612
                search: queryParameters,
                withCredentials: this.configuration.withCredentials
            },
            Object.assign({}, this.configuration, $options),
            retryTimesToGo => {
                $options = $options || {};
                $options.retryTimes = retryTimesToGo;

                return this.inventoryV1UnitTypesByIdPutWithHttpInfo(id, requestBody, $options);
            }
        )
    }

    /**
     * Get all unit types, or all unit types for a property
     * Get the list of unit types.
     * @param propertyId Return unit types for specific property
     * @param pageNumber Page number, starting from 1. Results in 204 if there are no items on that page. If the value is lower than 1, will be set to 1
     * @param pageSize Page size
     */
    private inventoryV1UnitTypesGetWithHttpInfo(propertyId?: string, pageNumber?: number, pageSize?: number, $options?: IRequestOptions): Observable<Response> {
        const path = this.basePath + '/inventory/v1/unit-types';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        if (propertyId !== undefined) {
            queryParameters.set('propertyId', <any>propertyId);
        }

        if (pageNumber !== undefined) {
            queryParameters.set('pageNumber', <any>pageNumber);
        }

        if (pageSize !== undefined) {
            queryParameters.set('pageSize', <any>pageSize);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'text/plain', 
            'application/json', 
            'text/json'
        ];

        // authentication (oauth2) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        return callApiEndpoint(
            this.http, 
            path,
            headers,
            {
                method: RequestMethod.Get,
                headers: headers,
                search: queryParameters,
                withCredentials: this.configuration.withCredentials
            },
            Object.assign({}, this.configuration, $options),
            retryTimesToGo => {
                $options = $options || {};
                $options.retryTimes = retryTimesToGo;

                return this.inventoryV1UnitTypesGetWithHttpInfo(propertyId, pageNumber, pageSize, $options);
            }
        )
    }

    /**
     * Create a unit type
     * Use this call to create a new unit type.
     * @param requestBody The definition of the unit type.
     */
    private inventoryV1UnitTypesPostWithHttpInfo(requestBody: models.CreateUnitTypeModel, $options?: IRequestOptions): Observable<Response> {
        const path = this.basePath + '/inventory/v1/unit-types';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'requestBody' is not null or undefined
        if (requestBody === null || requestBody === undefined) {
            throw new Error('Required parameter requestBody was null or undefined when calling inventoryV1UnitTypesPost.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json', 
            'text/json', 
            'application/json-patch+json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'text/plain', 
            'application/json', 
            'text/json'
        ];

        // authentication (oauth2) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        headers.set('Content-Type', 'application/json');

        return callApiEndpoint(
            this.http, 
            path,
            headers,
            {
                method: RequestMethod.Post,
                headers: headers,
                body: requestBody == null ? '' : JSON.stringify(requestBody), // https://github.com/angular/angular/issues/10612
                search: queryParameters,
                withCredentials: this.configuration.withCredentials
            },
            Object.assign({}, this.configuration, $options),
            retryTimesToGo => {
                $options = $options || {};
                $options.retryTimes = retryTimesToGo;

                return this.inventoryV1UnitTypesPostWithHttpInfo(requestBody, $options);
            }
        )
    }

    /**
     * Return total count of unit types
     * Return total count of unit types
     */
    private inventoryV1UnitTypescountGetWithHttpInfo($options?: IRequestOptions): Observable<Response> {
        const path = this.basePath + '/inventory/v1/unit-types/$count';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'text/plain', 
            'application/json', 
            'text/json'
        ];

        // authentication (oauth2) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        return callApiEndpoint(
            this.http, 
            path,
            headers,
            {
                method: RequestMethod.Get,
                headers: headers,
                search: queryParameters,
                withCredentials: this.configuration.withCredentials
            },
            Object.assign({}, this.configuration, $options),
            retryTimesToGo => {
                $options = $options || {};
                $options.retryTimes = retryTimesToGo;

                return this.inventoryV1UnitTypescountGetWithHttpInfo($options);
            }
        )
    }

}
