/**
 * Settings
 * Set up and change global account and property settings.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

import { FormBuilder, FormGroup }                                               from '@angular/forms';
import { ResponseModel }                                                        from '../../models';
import { getControl, adjustDefaultControls, prepareFormGroup }                  from '../../functions.model';
import { BuildFormOptions, ApaleoPropertyMetaData, ApaleoEnumPropertyMetaData } from '../../types';

export interface ReplaceTimeSliceDefinitionListModel {
    timeSliceDefinitions: Array<models.ReplaceTimeSliceDefinitionModel>;

}

export type ReplaceTimeSliceDefinitionListModelWithRawHttp = ReplaceTimeSliceDefinitionListModel & ResponseModel<ReplaceTimeSliceDefinitionListModel>;

export namespace ReplaceTimeSliceDefinitionListModel {
    export const $metaData = { 
        timeSliceDefinitions: Object.freeze({ 
            isRequired: true,
            type: 'Array<models.ReplaceTimeSliceDefinitionModel>',
            isListContainer: true,
        } as ApaleoPropertyMetaData),
    };

    export function $buildForm(fb: FormBuilder, options?: BuildFormOptions<ReplaceTimeSliceDefinitionListModel>): FormGroup {
        const defaultControls = { 
        };
        const group = fb.group(adjustDefaultControls(defaultControls, options));
        prepareFormGroup(group, $metaData, options);

        return group;
    }
}

