/**
 * Settings
 * Set up and change global account and property settings.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

import { FormBuilder, FormGroup }                                               from '@angular/forms';
import { ResponseModel }                                                        from '../../models';
import { getControl, adjustDefaultControls, prepareFormGroup }                  from '../../functions.model';
import { BuildFormOptions, ApaleoPropertyMetaData, ApaleoEnumPropertyMetaData } from '../../types';

export interface TimeSliceDefinitionItemModel {
    name: string;

    template: TimeSliceDefinitionItemModel.TemplateEnum;

    checkInTime: string;

    checkOutTime: string;

}
export namespace TimeSliceDefinitionItemModel {
    export enum TemplateEnumSet {
        DayUse = 'DayUse',
        OverNight = 'OverNight'
    }

    export type TemplateEnum = 'DayUse' | 'OverNight';

    export const TemplateEnumValues = Object.freeze(
        ['DayUse', 'OverNight'] as TemplateEnum[]);
}

export type TimeSliceDefinitionItemModelWithRawHttp = TimeSliceDefinitionItemModel & ResponseModel<TimeSliceDefinitionItemModel>;

export namespace TimeSliceDefinitionItemModel {
    export const $metaData = { 
        name: Object.freeze({ 
            isRequired: true,
            type: 'string',
            isPrimitiveType: true,
        } as ApaleoPropertyMetaData),
        template: Object.freeze({ 
            isRequired: true,
            type: 'string',
            isEnum: true,
            allowedEnumValues: TemplateEnumValues,
            isPrimitiveType: true,
        } as ApaleoEnumPropertyMetaData<TemplateEnum>),
        checkInTime: Object.freeze({ 
            isRequired: true,
            type: 'string',
            isPrimitiveType: true,
        } as ApaleoPropertyMetaData),
        checkOutTime: Object.freeze({ 
            isRequired: true,
            type: 'string',
            isPrimitiveType: true,
        } as ApaleoPropertyMetaData),
    };

    export function $buildForm(fb: FormBuilder, options?: BuildFormOptions<TimeSliceDefinitionItemModel>): FormGroup {
        const defaultControls = { 
            name: getControl($metaData.name, options, 'name'),
            template: getControl($metaData.template, options, 'template'),
            checkInTime: getControl($metaData.checkInTime, options, 'checkInTime'),
            checkOutTime: getControl($metaData.checkOutTime, options, 'checkOutTime'),
        };
        const group = fb.group(adjustDefaultControls(defaultControls, options));
        prepareFormGroup(group, $metaData, options);

        return group;
    }
}

