export * from './BookingApi';
import { BookingApi } from './BookingApi';
export * from './OfferApi';
import { OfferApi } from './OfferApi';
export * from './ReservationApi';
import { ReservationApi } from './ReservationApi';
export * from './ReservationActionsApi';
import { ReservationActionsApi } from './ReservationActionsApi';
export * from './UnitAvailabilityApi';
import { UnitAvailabilityApi } from './UnitAvailabilityApi';
export const APIS = [BookingApi, OfferApi, ReservationApi, ReservationActionsApi, UnitAvailabilityApi];
