/**
 * Apaleo Rates API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Inject, Injectable, Optional, LOCALE_ID }           from '@angular/core';
import { Http, Headers, URLSearchParams }                    from '@angular/http';
import { RequestMethod, RequestOptions, RequestOptionsArgs } from '@angular/http';
import { Response, ResponseContentType }                     from '@angular/http';

import { Observable }                                        from 'rxjs/Rx';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/mergeMap';
import 'rxjs/add/operator/delay';
import 'rxjs/add/operator/catch';

import * as models                                           from '../model/models';
import { BASE_PATH, COLLECTION_FORMATS }                     from '../../variables';
import { IRequestOptions, ResponseModel, ResponseHeaders }   from '../../models';
import { Configuration }                                     from '../../configuration';
import { callApiEndpoint }                                   from '../../functions';

/* tslint:disable:no-unused-variable member-ordering */


@Injectable()
export class OfferApi {
    public defaultHeaders: Headers = new Headers();

    constructor(
        protected readonly http: Http, 
        protected readonly configuration: Configuration,
        @Inject(LOCALE_ID) protected readonly locale: string, 
        @Inject(BASE_PATH) protected readonly basePath: string) {

        this.defaultHeaders.append('Accept-Language', locale);
    }

    /**
     * Get offers for one specifc stay
     * Get offers for a specific property, arrival and departure date.
     * @param propertyCode The property code
     * @param arrival The arrival date
     * @param departure The departure date
     */
    public ratesV1OffersStayGet(propertyCode: string, arrival: Date, departure: Date, $options?: IRequestOptions)
        : Observable<models.StayOffersModel | undefined> {
        return this.ratesV1OffersStayGetWithRawHttp(propertyCode, arrival, departure, $options)
            .map(response => response.$hasValue(response) ? response : undefined);
    }


    /**
     * Get offers for one specifc stay
     * Get offers for a specific property, arrival and departure date.
     * @param propertyCode The property code
     * @param arrival The arrival date
     * @param departure The departure date
     */
    public ratesV1OffersStayGetWithRawHttp(propertyCode: string, arrival: Date, departure: Date, $options?: IRequestOptions)
        : Observable<ResponseModel<models.StayOffersModel>> {
        return this.ratesV1OffersStayGetWithHttpInfo(propertyCode, arrival, departure, $options)
            .map((response: Response) => new ResponseModel(response));
    }


    /**
     * Get offers for one specifc stay
     * Get offers for a specific property, arrival and departure date.
     * @param propertyCode The property code
     * @param arrival The arrival date
     * @param departure The departure date
     */
    private ratesV1OffersStayGetWithHttpInfo(propertyCode: string, arrival: Date, departure: Date, $options?: IRequestOptions): Observable<Response> {
        const path = this.basePath + '/rates/v1/offers/stay';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'propertyCode' is not null or undefined
        if (propertyCode === null || propertyCode === undefined) {
            throw new Error('Required parameter propertyCode was null or undefined when calling ratesV1OffersStayGet.');
        }
        // verify required parameter 'arrival' is not null or undefined
        if (arrival === null || arrival === undefined) {
            throw new Error('Required parameter arrival was null or undefined when calling ratesV1OffersStayGet.');
        }
        // verify required parameter 'departure' is not null or undefined
        if (departure === null || departure === undefined) {
            throw new Error('Required parameter departure was null or undefined when calling ratesV1OffersStayGet.');
        }
        if (propertyCode !== undefined) {
            queryParameters.set('propertyCode', <any>propertyCode);
        }

        if (arrival !== undefined) {
            queryParameters.set('arrival', <any>arrival.toISOString());
        }

        if (departure !== undefined) {
            queryParameters.set('departure', <any>departure.toISOString());
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'text/plain', 
            'application/json', 
            'text/json'
        ];

        // authentication (oauth2) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        return callApiEndpoint(
            this.http, 
            path,
            headers,
            {
                method: RequestMethod.Get,
                headers: headers,
                search: queryParameters
            },
            Object.assign({}, this.configuration, $options),
            retryTimesToGo => {
                $options = $options || {};
                $options.retryTimes = retryTimesToGo;

                return this.ratesV1OffersStayGetWithHttpInfo(propertyCode, arrival, departure, $options);
            }
        )
    }

}
