/**
 * Apaleo Account API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * With this request you can create a new account
 */
import { FormBuilder, FormGroup }                         from '@angular/forms';
import { IBuildFormOptions, IApaleoPropertyMetaData }     from '../../types';
import { ResponseModel }                                  from '../../models';
import { getControl, adjustDefaultControls, setMetaData } from '../../functions.model';

export interface AccountModel {
    /**
     * The code for the account that can be shown in reports and table views
     */
    code?: string;

    /**
     * The name for the account, which usually should be the company name
     */
    name?: string;

    /**
     * The description for the account
     */
    description?: string;

    /**
     * The default language code for the account
     */
    defaultLanguage?: string;

    /**
     * The URL of the account logo
     */
    logoUrl?: string;

    /**
     * The location of the account
     */
    location?: models.LocationModel;

}

export type AccountModelWithRawHttp = AccountModel & ResponseModel<AccountModel>;

export namespace AccountModel {
    export const $metaData = { 
        code: Object.freeze({ 
            type: 'string',
            isPrimitiveType: true,
        } as IApaleoPropertyMetaData),
        name: Object.freeze({ 
            type: 'string',
            isPrimitiveType: true,
        } as IApaleoPropertyMetaData),
        description: Object.freeze({ 
            type: 'string',
            isPrimitiveType: true,
        } as IApaleoPropertyMetaData),
        defaultLanguage: Object.freeze({ 
            type: 'string',
            isPrimitiveType: true,
        } as IApaleoPropertyMetaData),
        logoUrl: Object.freeze({ 
            type: 'string',
            isPrimitiveType: true,
        } as IApaleoPropertyMetaData),
        location: Object.freeze({ 
            type: 'models.LocationModel',
        } as IApaleoPropertyMetaData),
    };

    export function $buildForm(fb: FormBuilder, options?: IBuildFormOptions<AccountModel>): FormGroup {
        const defaultControls = { 
            code: getControl($metaData.code, options, 'code'),
            name: getControl($metaData.name, options, 'name'),
            description: getControl($metaData.description, options, 'description'),
            defaultLanguage: getControl($metaData.defaultLanguage, options, 'defaultLanguage'),
            logoUrl: getControl($metaData.logoUrl, options, 'logoUrl'),
            location: models.LocationModel.$buildForm(fb),
        };
        const group = fb.group(adjustDefaultControls(defaultControls, options));
        setMetaData(group, $metaData);

        return group;
    }
}

