/**
 * Apaleo Bookings API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * With this request you can create a reservation
 */
import { Validators, FormBuilder, ValidatorFn, FormGroup, AbstractControl } from '@angular/forms';
import { IBuildFormOptions, IControlFactoryOptions, Control }               from '../../types';
import { IApaleoAbstractControl, IApaleoControlMetaData }                   from '../../types';
import { ResponseModel }                                                    from '../../models';
import { getControl, getControlOptions, adjustDefaultControls }             from '../../functions';

export interface CreateReservationModel {
    /**
     * The PropertyId for the reservation
     */
    propertyId: number;

    checkInTime: string;

    checkOutTime: string;

    adults: number;

    children: number;

    guestTitle: string;

    firstName: string;

    middleInitial?: string;

    lastName: string;

    email?: string;

    phone?: string;

    street?: string;

    number?: string;

    city: string;

    zipCode: string;

    countryCode: string;

    ratePlanId: number;

}

export type CreateReservationModelWithRawHttp = CreateReservationModel & ResponseModel<CreateReservationModel>;

export namespace CreateReservationModel {
    export const $validators = {
        propertyId: (() => [
            Validators.required,
        ]),
        checkInTime: (() => [
            Validators.required,
        ]),
        checkOutTime: (() => [
            Validators.required,
        ]),
        adults: (() => [
            Validators.required,
        ]),
        children: (() => [
            Validators.required,
        ]),
        guestTitle: (() => [
            Validators.required,
        ]),
        firstName: (() => [
            Validators.required,
            Validators.maxLength(25),
        ]),
        middleInitial: (() => [
            Validators.maxLength(5),
        ]),
        lastName: (() => [
            Validators.required,
            Validators.maxLength(40),
        ]),
        email: (() => [
        ]),
        phone: (() => [
        ]),
        street: (() => [
            Validators.maxLength(40),
        ]),
        number: (() => [
        ]),
        city: (() => [
            Validators.required,
            Validators.maxLength(25),
        ]),
        zipCode: (() => [
            Validators.required,
            Validators.maxLength(10),
        ]),
        countryCode: (() => [
            Validators.required,
            Validators.maxLength(2),
        ]),
        ratePlanId: (() => [
            Validators.required,
        ]),
    };

    export const $controls = { 
        propertyId: ((options?: IControlFactoryOptions<number>) => getControl($validators.propertyId(), options)),
        checkInTime: ((options?: IControlFactoryOptions<string>) => getControl($validators.checkInTime(), options)),
        checkOutTime: ((options?: IControlFactoryOptions<string>) => getControl($validators.checkOutTime(), options)),
        adults: ((options?: IControlFactoryOptions<number>) => getControl($validators.adults(), options)),
        children: ((options?: IControlFactoryOptions<number>) => getControl($validators.children(), options)),
        guestTitle: ((options?: IControlFactoryOptions<string>) => getControl($validators.guestTitle(), options)),
        firstName: ((options?: IControlFactoryOptions<string>) => getControl($validators.firstName(), options)),
        middleInitial: ((options?: IControlFactoryOptions<string>) => getControl($validators.middleInitial(), options)),
        lastName: ((options?: IControlFactoryOptions<string>) => getControl($validators.lastName(), options)),
        email: ((options?: IControlFactoryOptions<string>) => getControl($validators.email(), options)),
        phone: ((options?: IControlFactoryOptions<string>) => getControl($validators.phone(), options)),
        street: ((options?: IControlFactoryOptions<string>) => getControl($validators.street(), options)),
        number: ((options?: IControlFactoryOptions<string>) => getControl($validators.number(), options)),
        city: ((options?: IControlFactoryOptions<string>) => getControl($validators.city(), options)),
        zipCode: ((options?: IControlFactoryOptions<string>) => getControl($validators.zipCode(), options)),
        countryCode: ((options?: IControlFactoryOptions<string>) => getControl($validators.countryCode(), options)),
        ratePlanId: ((options?: IControlFactoryOptions<number>) => getControl($validators.ratePlanId(), options)),
    };

    export const $metaData = { 
        propertyId: { 
            type: 'number',
        } as IApaleoControlMetaData,
        checkInTime: { 
            type: 'string',
        } as IApaleoControlMetaData,
        checkOutTime: { 
            type: 'string',
        } as IApaleoControlMetaData,
        adults: { 
            type: 'number',
        } as IApaleoControlMetaData,
        children: { 
            type: 'number',
        } as IApaleoControlMetaData,
        guestTitle: { 
            type: 'string',
        } as IApaleoControlMetaData,
        firstName: { 
            maxLength: 25,
            type: 'string',
        } as IApaleoControlMetaData,
        middleInitial: { 
            maxLength: 5,
            type: 'string',
        } as IApaleoControlMetaData,
        lastName: { 
            maxLength: 40,
            type: 'string',
        } as IApaleoControlMetaData,
        email: { 
            type: 'string',
        } as IApaleoControlMetaData,
        phone: { 
            type: 'string',
        } as IApaleoControlMetaData,
        street: { 
            maxLength: 40,
            type: 'string',
        } as IApaleoControlMetaData,
        number: { 
            type: 'string',
        } as IApaleoControlMetaData,
        city: { 
            maxLength: 25,
            type: 'string',
        } as IApaleoControlMetaData,
        zipCode: { 
            maxLength: 10,
            type: 'string',
        } as IApaleoControlMetaData,
        countryCode: { 
            maxLength: 2,
            type: 'string',
        } as IApaleoControlMetaData,
        ratePlanId: { 
            type: 'number',
        } as IApaleoControlMetaData,
    };

    export function $buildForm(fb: FormBuilder, options?: IBuildFormOptions<CreateReservationModel>) {
        const defaultControls = { 
            propertyId: $controls.propertyId(getControlOptions(options, 'propertyId')),
            checkInTime: $controls.checkInTime(getControlOptions(options, 'checkInTime')),
            checkOutTime: $controls.checkOutTime(getControlOptions(options, 'checkOutTime')),
            adults: $controls.adults(getControlOptions(options, 'adults')),
            children: $controls.children(getControlOptions(options, 'children')),
            guestTitle: $controls.guestTitle(getControlOptions(options, 'guestTitle')),
            firstName: $controls.firstName(getControlOptions(options, 'firstName')),
            middleInitial: $controls.middleInitial(getControlOptions(options, 'middleInitial')),
            lastName: $controls.lastName(getControlOptions(options, 'lastName')),
            email: $controls.email(getControlOptions(options, 'email')),
            phone: $controls.phone(getControlOptions(options, 'phone')),
            street: $controls.street(getControlOptions(options, 'street')),
            number: $controls.number(getControlOptions(options, 'number')),
            city: $controls.city(getControlOptions(options, 'city')),
            zipCode: $controls.zipCode(getControlOptions(options, 'zipCode')),
            countryCode: $controls.countryCode(getControlOptions(options, 'countryCode')),
            ratePlanId: $controls.ratePlanId(getControlOptions(options, 'ratePlanId')),
        };
        const group = fb.group(adjustDefaultControls(defaultControls, options)!);

        (<IApaleoAbstractControl><any>group.controls['propertyId']).apaleoMetaData = $metaData.propertyId;
        (<IApaleoAbstractControl><any>group.controls['checkInTime']).apaleoMetaData = $metaData.checkInTime;
        (<IApaleoAbstractControl><any>group.controls['checkOutTime']).apaleoMetaData = $metaData.checkOutTime;
        (<IApaleoAbstractControl><any>group.controls['adults']).apaleoMetaData = $metaData.adults;
        (<IApaleoAbstractControl><any>group.controls['children']).apaleoMetaData = $metaData.children;
        (<IApaleoAbstractControl><any>group.controls['guestTitle']).apaleoMetaData = $metaData.guestTitle;
        (<IApaleoAbstractControl><any>group.controls['firstName']).apaleoMetaData = $metaData.firstName;
        (<IApaleoAbstractControl><any>group.controls['middleInitial']).apaleoMetaData = $metaData.middleInitial;
        (<IApaleoAbstractControl><any>group.controls['lastName']).apaleoMetaData = $metaData.lastName;
        (<IApaleoAbstractControl><any>group.controls['email']).apaleoMetaData = $metaData.email;
        (<IApaleoAbstractControl><any>group.controls['phone']).apaleoMetaData = $metaData.phone;
        (<IApaleoAbstractControl><any>group.controls['street']).apaleoMetaData = $metaData.street;
        (<IApaleoAbstractControl><any>group.controls['number']).apaleoMetaData = $metaData.number;
        (<IApaleoAbstractControl><any>group.controls['city']).apaleoMetaData = $metaData.city;
        (<IApaleoAbstractControl><any>group.controls['zipCode']).apaleoMetaData = $metaData.zipCode;
        (<IApaleoAbstractControl><any>group.controls['countryCode']).apaleoMetaData = $metaData.countryCode;
        (<IApaleoAbstractControl><any>group.controls['ratePlanId']).apaleoMetaData = $metaData.ratePlanId;

        return group;
    }
}

