/**
 * Apaleo Inventory API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

import { Validators, FormBuilder, ValidatorFn, FormGroup, AbstractControl } from '@angular/forms';
import { IBuildFormOptions, IControlFactoryOptions, Control }               from '../../types';
import { IApaleoAbstractControl, IApaleoControlMetaData }                   from '../../types';
import { ResponseModel }                                                    from '../../models';
import { getControl, getControlOptions, adjustDefaultControls }             from '../../functions';

export interface CreateUnitTypeModel {
    /**
     * The code for the unit type that can be shown in reports and table views
     */
    code: string;

    /**
     * The code of the property where unit type will be created
     */
    propertyCode: string;

    /**
     * The name for the unit type
     */
    name: { [key: string]: string; };

    /**
     * The description for the unit type
     */
    description: { [key: string]: string; };

    /**
     * Minimum number of persons for the unit type
     */
    minPersons: number;

    /**
     * Maximum number of persons for the unit type
     */
    maxPersons: number;

}

export type CreateUnitTypeModelWithRawHttp = CreateUnitTypeModel & ResponseModel<CreateUnitTypeModel>;

export namespace CreateUnitTypeModel {
    export const $validators = {
        code: (() => [
            Validators.required,
            Validators.minLength(3),
            Validators.maxLength(10),
        ]),
        propertyCode: (() => [
            Validators.required,
        ]),
        name: (() => [
            Validators.required,
        ]),
        description: (() => [
            Validators.required,
        ]),
        minPersons: (() => [
            Validators.required,
        ]),
        maxPersons: (() => [
            Validators.required,
        ]),
    };

    export const $controls = { 
        code: ((options?: IControlFactoryOptions<string>) => getControl($validators.code(), options)),
        propertyCode: ((options?: IControlFactoryOptions<string>) => getControl($validators.propertyCode(), options)),
        minPersons: ((options?: IControlFactoryOptions<number>) => getControl($validators.minPersons(), options)),
        maxPersons: ((options?: IControlFactoryOptions<number>) => getControl($validators.maxPersons(), options)),
    };

    export const $metaData = { 
        code: { 
            maxLength: 10,
            type: 'string',
        } as IApaleoControlMetaData,
        propertyCode: { 
            type: 'string',
        } as IApaleoControlMetaData,
        name: { 
            type: '{ [key: string]: string; }',
        } as IApaleoControlMetaData,
        description: { 
            type: '{ [key: string]: string; }',
        } as IApaleoControlMetaData,
        minPersons: { 
            type: 'number',
        } as IApaleoControlMetaData,
        maxPersons: { 
            type: 'number',
        } as IApaleoControlMetaData,
    };

    export function $buildForm(fb: FormBuilder, options?: IBuildFormOptions<CreateUnitTypeModel>) {
        const defaultControls = { 
            code: $controls.code(getControlOptions(options, 'code')),
            propertyCode: $controls.propertyCode(getControlOptions(options, 'propertyCode')),
            minPersons: $controls.minPersons(getControlOptions(options, 'minPersons')),
            maxPersons: $controls.maxPersons(getControlOptions(options, 'maxPersons')),
        };
        const group = fb.group(adjustDefaultControls(defaultControls, options)!);

        (<IApaleoAbstractControl><any>group.controls['code']).apaleoMetaData = $metaData.code;
        (<IApaleoAbstractControl><any>group.controls['propertyCode']).apaleoMetaData = $metaData.propertyCode;
        (<IApaleoAbstractControl><any>group.controls['minPersons']).apaleoMetaData = $metaData.minPersons;
        (<IApaleoAbstractControl><any>group.controls['maxPersons']).apaleoMetaData = $metaData.maxPersons;

        return group;
    }
}

