/**
 * Apaleo Inventory API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * With this request you can create a new property
 */
import { Validators } from '@angular/forms';
import { ValidatorsFactory, ControlFactory, Control } from '../../types';

export interface PropertyModel {
    /**
     * The code for the property that can be shown in reports and table views
     */
    code: string;

    /**
     * The name for the property
     */
    name: { [key: string]: string; };

    /**
     * The description for the property
     */
    description: { [key: string]: string; };

    /**
     * The location of the property
     */
    location: models.Location;

}

export interface PropertyModel$Form<T> {
    code: T;
    name: T;
    description: T;
    location: T;
}

export interface PropertyModel$ValidatorFactories extends PropertyModel$Form<ValidatorsFactory> {}
export interface PropertyModel$ControlFactories extends PropertyModel$Form<ControlFactory> {}
export interface PropertyModel$FormBuiler extends PropertyModel$Form<Control> {}

const $validators: PropertyModel$ValidatorFactories = {
    code: (() => [
        Validators.required,
        
        Validators.maxLength(10),
    ]),
    name: (() => [
        Validators.required,
        
        
    ]),
    description: (() => [
        Validators.required,
        
        
    ]),
    location: (() => [
        Validators.required,
        
        
    ]),
}

const $controls: PropertyModel$ControlFactories = {
    code: (() => [null, Validators.compose($validators.code())]),
    name: (() => [null, Validators.compose($validators.name())]),
    description: (() => [null, Validators.compose($validators.description())]),
    location: (() => [null, Validators.compose($validators.location())]),
}

export const PropertyModel = {
    $validators: $validators,
    $controls: $controls,
    $formGroup: (() => {
        return {
            code: $controls.code(),
            name: $controls.name(),
            description: $controls.description(),
            location: models.Location.$formGroup(),
        };
    }) as (() => PropertyModel$FormBuiler),
}

