/**
 * Apaleo Inventory API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * With this request you can modify a property
 */
import { Validators, FormBuilder, ValidatorFn, FormGroup }          from '@angular/forms';
import { ValidatorsFactory, ControlFactory, Control }               from '../../types';
import { IApaleoAbstractControl, IApaleoControlMetaData, Optional } from '../../types';
import { ResponseModel }                                            from '../../models';

export interface ReplacePropertyModel {
    /**
     * The name for the property
     */
    name: { [key: string]: string; };

    /**
     * The description for the property
     */
    description: { [key: string]: string; };

    /**
     * The location of the property
     */
    location: models.Location;

}

export type ReplacePropertyModelWithRawHttp = ReplacePropertyModel & ResponseModel<ReplacePropertyModel>;

export interface ReplacePropertyModel$Form<T> {
    name: T;
    description: T;
    location: T;
}

export interface ReplacePropertyModel$ValidatorFactories extends ReplacePropertyModel$Form<ValidatorsFactory> {}
export interface ReplacePropertyModel$ControlFactories extends ReplacePropertyModel$Form<ControlFactory> {}
export interface ReplacePropertyModel$Control extends ReplacePropertyModel$Form<Control | FormGroup> {}
export interface ReplacePropertyModel$ControlMetaData extends ReplacePropertyModel$Form<IApaleoControlMetaData> {}

export namespace ReplacePropertyModel {
    export const $validators: ReplacePropertyModel$ValidatorFactories = {
        name: (() => [
            Validators.required,
            
            
        ]),
        description: (() => [
            Validators.required,
            
            
        ]),
        location: (() => [
            Validators.required,
            
            
        ]),
    };

    export const $controls: ReplacePropertyModel$ControlFactories = {
        name: (() => [null, Validators.compose($validators.name())]),
        description: (() => [null, Validators.compose($validators.description())]),
        location: (() => [null, Validators.compose($validators.location())]),
    };

    export const $metaData: ReplacePropertyModel$ControlMetaData = {
        name: {
            
            
            type: '{ [key: string]: string; }',
            
        },
        description: {
            
            
            type: '{ [key: string]: string; }',
            
        },
        location: {
            
        },
    };

    export function $buildForm(fb: FormBuilder, specificControls?: Optional<ReplacePropertyModel$Control>, additionalControls?: { [name: string]: (Control | FormGroup) }) {
        const defaultControls = {
            name: $controls.name(),
            description: $controls.description(),
            location: models.Location.$buildForm(fb),
        };

        const group = fb.group(Object.assign(defaultControls, specificControls, additionalControls));

    
        const nameCtrl: IApaleoAbstractControl = <any>group.controls['name'];
        nameCtrl.apaleoMetaData = $metaData.name;
    
    
        const descriptionCtrl: IApaleoAbstractControl = <any>group.controls['description'];
        descriptionCtrl.apaleoMetaData = $metaData.description;
    
    

        return group;
    }
}

