/**
 * Apaleo Inventory API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

import { Validators, FormBuilder, ValidatorFn, FormGroup, AbstractControl }  from '@angular/forms';
import { IBuildFormOptions, IControlFactoryOptions, Control }                from '../../types';
import { IApaleoAbstractControl, IApaleoControlMetaData }                    from '../../types';
import { ResponseModel }                                                     from '../../models';
import { getControl, getControlOptions, adjustDefaultControls, setMetaData } from '../../functions';

export interface UnitModel {
    /**
     * The unit id
     */
    id?: string;

    /**
     * The name for the unit
     */
    name?: string;

    /**
     * The description for the unit
     */
    description?: { [key: string]: string; };

    /**
     * The property to which the unit belongs to
     */
    property?: models.EmbeddedPropertyModel;

    /**
     * The unit type
     */
    unitType?: models.EmbeddedUnitTypeModel;

    /**
     * Minimum number of persons for the unit
     */
    minPersons?: number;

    /**
     * Maximum number of persons for the unit
     */
    maxPersons?: number;

}

export type UnitModelWithRawHttp = UnitModel & ResponseModel<UnitModel>;

export namespace UnitModel {
    export const $validators = {
        id: (() => [
        ]),
        name: (() => [
        ]),
        description: (() => [
        ]),
        property: (() => [
        ]),
        unitType: (() => [
        ]),
        minPersons: (() => [
        ]),
        maxPersons: (() => [
        ]),
    };

    export const $controls = { 
        id: ((options?: IControlFactoryOptions<string>) => getControl($validators.id(), options)),
        name: ((options?: IControlFactoryOptions<string>) => getControl($validators.name(), options)),
        minPersons: ((options?: IControlFactoryOptions<number>) => getControl($validators.minPersons(), options)),
        maxPersons: ((options?: IControlFactoryOptions<number>) => getControl($validators.maxPersons(), options)),
    };

    export const $metaData = { 
        id: { 
            type: 'string',
        } as IApaleoControlMetaData,
        name: { 
            type: 'string',
        } as IApaleoControlMetaData,
        description: { 
            type: '{ [key: string]: string; }',
        } as IApaleoControlMetaData,
        minPersons: { 
            type: 'number',
        } as IApaleoControlMetaData,
        maxPersons: { 
            type: 'number',
        } as IApaleoControlMetaData,
    };

    export function $buildForm(fb: FormBuilder, options?: IBuildFormOptions<UnitModel>) {
        const defaultControls = { 
            id: $controls.id(getControlOptions(options, 'id')),
            name: $controls.name(getControlOptions(options, 'name')),
            property: models.EmbeddedPropertyModel.$buildForm(fb),
            unitType: models.EmbeddedUnitTypeModel.$buildForm(fb),
            minPersons: $controls.minPersons(getControlOptions(options, 'minPersons')),
            maxPersons: $controls.maxPersons(getControlOptions(options, 'maxPersons')),
        };
        const group = fb.group(adjustDefaultControls(defaultControls, options)!);

        setMetaData(<any>group.controls.id, $metaData.id);
        setMetaData(<any>group.controls.name, $metaData.name);
        setMetaData(<any>group.controls.minPersons, $metaData.minPersons);
        setMetaData(<any>group.controls.maxPersons, $metaData.maxPersons);

        return group;
    }
}

