/**
 * Apaleo Inventory API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * With this request you can create a new property
 */
import { Validators, FormBuilder, ValidatorFn, FormGroup }          from '@angular/forms';
import { ValidatorsFactory, ControlFactory, Control }               from '../../types';
import { IApaleoAbstractControl, IApaleoControlMetaData, Optional } from '../../types';
import { ResponseModel }                                            from '../../models';

export interface UnitTypeModel {
    /**
     * The unit type id
     */
    id?: string;

    /**
     * The code for the unit type that can be shown in reports and table views
     */
    code?: string;

    /**
     * The property to which the unit type belongs to
     */
    propertyCode?: string;

    /**
     * The name for the unit type
     */
    name?: { [key: string]: string; };

    /**
     * The description for the unit type
     */
    description?: { [key: string]: string; };

    /**
     * Minimum number of persons for the unit type
     */
    minPersons?: number;

    /**
     * Maximum number of persons for the unit type
     */
    maxPersons?: number;

}

export type UnitTypeModelWithRawHttp = UnitTypeModel & ResponseModel<UnitTypeModel>;

export interface UnitTypeModel$Form<T> {
    id: T;
    code: T;
    propertyCode: T;
    name: T;
    description: T;
    minPersons: T;
    maxPersons: T;
}

export interface UnitTypeModel$ValidatorFactories extends UnitTypeModel$Form<ValidatorsFactory> {}
export interface UnitTypeModel$ControlFactories extends UnitTypeModel$Form<ControlFactory> {}
export interface UnitTypeModel$Control extends UnitTypeModel$Form<Control | FormGroup> {}
export interface UnitTypeModel$ControlMetaData extends UnitTypeModel$Form<IApaleoControlMetaData> {}

export namespace UnitTypeModel {
    export const $validators: UnitTypeModel$ValidatorFactories = {
        id: (() => [
            
            
            
        ]),
        code: (() => [
            
            
            
        ]),
        propertyCode: (() => [
            
            
            
        ]),
        name: (() => [
            
            
            
        ]),
        description: (() => [
            
            
            
        ]),
        minPersons: (() => [
            
            
            
        ]),
        maxPersons: (() => [
            
            
            
        ]),
    };

    export const $controls: UnitTypeModel$ControlFactories = {
        id: (() => [null, Validators.compose($validators.id())]),
        code: (() => [null, Validators.compose($validators.code())]),
        propertyCode: (() => [null, Validators.compose($validators.propertyCode())]),
        name: (() => [null, Validators.compose($validators.name())]),
        description: (() => [null, Validators.compose($validators.description())]),
        minPersons: (() => [null, Validators.compose($validators.minPersons())]),
        maxPersons: (() => [null, Validators.compose($validators.maxPersons())]),
    };

    export const $metaData: UnitTypeModel$ControlMetaData = {
        id: {
            
            
            type: 'string',
            
        },
        code: {
            
            
            type: 'string',
            
        },
        propertyCode: {
            
            
            type: 'string',
            
        },
        name: {
            
            
            type: '{ [key: string]: string; }',
            
        },
        description: {
            
            
            type: '{ [key: string]: string; }',
            
        },
        minPersons: {
            
            
            type: 'number',
            
        },
        maxPersons: {
            
            
            type: 'number',
            
        },
    };

    export function $buildForm(fb: FormBuilder, specificControls?: Optional<UnitTypeModel$Control>, additionalControls?: { [name: string]: (Control | FormGroup) }) {
        const defaultControls = {
            id: $controls.id(),
            code: $controls.code(),
            propertyCode: $controls.propertyCode(),
            name: $controls.name(),
            description: $controls.description(),
            minPersons: $controls.minPersons(),
            maxPersons: $controls.maxPersons(),
        };

        const group = fb.group(Object.assign(defaultControls, specificControls, additionalControls));

    
        const idCtrl: IApaleoAbstractControl = <any>group.controls['id'];
        idCtrl.apaleoMetaData = $metaData.id;
    
    
        const codeCtrl: IApaleoAbstractControl = <any>group.controls['code'];
        codeCtrl.apaleoMetaData = $metaData.code;
    
    
        const propertyCodeCtrl: IApaleoAbstractControl = <any>group.controls['propertyCode'];
        propertyCodeCtrl.apaleoMetaData = $metaData.propertyCode;
    
    
        const nameCtrl: IApaleoAbstractControl = <any>group.controls['name'];
        nameCtrl.apaleoMetaData = $metaData.name;
    
    
        const descriptionCtrl: IApaleoAbstractControl = <any>group.controls['description'];
        descriptionCtrl.apaleoMetaData = $metaData.description;
    
    
        const minPersonsCtrl: IApaleoAbstractControl = <any>group.controls['minPersons'];
        minPersonsCtrl.apaleoMetaData = $metaData.minPersons;
    
    
        const maxPersonsCtrl: IApaleoAbstractControl = <any>group.controls['maxPersons'];
        maxPersonsCtrl.apaleoMetaData = $metaData.maxPersons;
    

        return group;
    }
}

